# -*- coding: utf-8 -*-
"""4_15_2026_Econ238.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oPnpxeEvJVTci0-IPEHVqF_Sgfpcm3do

# Testing Grounds for the code
"""

import cvxpy as cp
import numpy as np
import time

# Define f and gradient g
def f(x):
    return (x-4)**2 + 7

def g(x):
    return 2*x - 8

# Bounds
x_low, x_high = -12, 11
tolerance = 0.0004

# --- Initialize ---
x_init = x_low
constraints_list = []  # will store (f(xi), g(xi), xi) tuples

# Add initial cutting plane at x = -0.5
constraints_list.append((f(x_init), g(x_init), x_init))

# Initialize bounds
upper_bound = f(x_init)
lower_bound = -10000.0

print(f"{'Iter':>4} | {'x*':>8} | {'theta*':>10} | {'UB':>10} | {'LB':>12} | {'UB-LB':>12}")
print("-" * 70)

start_time = time.process_time()
for iteration in range(1, 1000):
    # --- Define CVXPY problem ---
    x = cp.Variable()
    theta = cp.Variable()

    # Bound constraints on x
    cvxpy_constraints = [x >= x_low, x <= x_high]

    # Add all cutting plane constraints: theta >= f(xi) + g(xi)*(x - xi)
    for (fi, gi, xi) in constraints_list:
        cvxpy_constraints.append(theta >= fi + gi * (x - xi))

    # Solve
    prob = cp.Problem(cp.Minimize(theta), cvxpy_constraints)
    prob.solve(solver=cp.HIGHS)

    x_star = x.value
    theta_star = theta.value

    # Update bounds
    lower_bound = theta_star          # LP gives a valid lower bound
    upper_bound = min(upper_bound, f(x_star))  # best true f value seen so far

    print(f"{iteration:>4} | {x_star:>8.4f} | {theta_star:>10.4f} | {upper_bound:>10.4f} | {lower_bound:>12.4f} | {upper_bound - lower_bound:>12.6f}")

    # --- Check convergence ---
    if upper_bound - lower_bound <= tolerance:
        print(f"\nConverged at iteration {iteration}!")
        print(f"Optimal x ≈ {x_star:.6f}")
        print(f"Optimal f(x) ≈ {f(x_star):.6f}")
        break

    # --- Add new cutting plane at x_star ---
    constraints_list.append((f(x_star), g(x_star), x_star))

"""# Problem 1

---
cutting plane problem

"""

import cvxpy as cp
import numpy as np
import matplotlib.pyplot as plt
import time
# ── f and gradient ────────────────────────────────────────────────────────────
def f(x):  return x**2
def g(x):  return 2*x

# ── settings ──────────────────────────────────────────────────────────────────
x_low, x_high = -0.5, 1.0
tolerance     = 0.0001
x_init        = x_low

constraints_list = [(f(x_init), g(x_init), x_init)]
upper_bound      = f(x_init)
lower_bound      = -10000.0

history = []   # (iter, x_star, theta_star, UB, LB)

print(f"{'Iter':>4} | {'x*':>8} | {'theta*':>10} | {'UB':>10} | {'LB':>12} | {'Gap':>12}")
print("-" * 70)
start_time = time.process_time()

# ── cutting-plane loop ────────────────────────────────────────────────────────
for iteration in range(1, 1000):
    x     = cp.Variable()
    theta = cp.Variable()

    cvxpy_constraints = [x >= x_low, x <= x_high]
    for (fi, gi, xi) in constraints_list:
        cvxpy_constraints.append(theta >= fi + gi * (x - xi))

    prob = cp.Problem(cp.Minimize(theta), cvxpy_constraints)
    prob.solve(solver=cp.HIGHS)

    x_star     = x.value
    theta_star = theta.value

    lower_bound = theta_star
    upper_bound = min(upper_bound, f(x_star))
    gap         = upper_bound - lower_bound

    history.append((iteration, x_star, theta_star, upper_bound, lower_bound))
    print(f"{iteration:>4} | {x_star:>8.4f} | {theta_star:>10.4f} | "
          f"{upper_bound:>10.4f} | {lower_bound:>12.4f} | {gap:>12.6f}")

    if gap <= tolerance:
        print(f"\nConverged at iteration {iteration}!")
        print(f"Optimal x  ≈ {x_star:.6f}")
        print(f"Optimal f  ≈ {f(x_star):.6f}")
        break

    constraints_list.append((f(x_star), g(x_star), x_star))
cpu_time = time.process_time() - start_time
print("Time:", cpu_time)
# ── unpack history ────────────────────────────────────────────────────────────
iters  = [h[0] for h in history]
xs     = [h[1] for h in history]
UBs    = [h[3] for h in history]
LBs    = [h[4] for h in history]
gaps   = [u - l for u, l in zip(UBs, LBs)]

# ── figure layout ─────────────────────────────────────────────────────────────
fig, (ax_curve, ax_conv, ax_gap) = plt.subplots(1, 3, figsize=(14, 4))
fig.suptitle("Cutting Plane Method — f(x) = x^2 on [-0.5, 1]")

# ── LEFT: f(x) curve + trial points ──────────────────────────────────────────
xx = np.linspace(x_low - 0.05, x_high + 0.05, 400)

ax_curve.plot(xx, f(xx), label="f(x) = x^2")

# draw cutting planes
for (fi, gi, xi) in constraints_list:
    ax_curve.plot(xx, fi + gi * (xx - xi), color="gray", linewidth=0.8, alpha=0.6)

# trial points
ax_curve.scatter(xs, [f(x) for x in xs], color="orange", zorder=5, label="Trial points")
ax_curve.scatter(xs[-1], f(xs[-1]), color="red", zorder=6, s=80, label=f"Optimal x*={xs[-1]:.4f}")

ax_curve.set_xlabel("x")
ax_curve.set_ylabel("f(x)")
ax_curve.set_title("f(x) with cutting planes")
ax_curve.legend()

# ── MIDDLE: UB and LB vs iteration ───────────────────────────────────────────
ax_conv.plot(iters, UBs, marker="o", label="UB_k")
ax_conv.plot(iters, LBs, marker="s", label="LB_k")

ax_conv.set_xlabel("Iteration k")
ax_conv.set_ylabel("Bound value")
ax_conv.set_title("UB and LB per iteration")
ax_conv.legend()

# ── RIGHT: gap vs iteration ───────────────────────────────────────────────────
ax_gap.plot(iters, gaps, marker="o", label="Gap_k = UB_k - LB_k")
ax_gap.axhline(tolerance, linestyle="--", color="red", label=f"Tolerance = {tolerance}")

ax_gap.set_xlabel("Iteration k")
ax_gap.set_ylabel("Gap")
ax_gap.set_title("Optimality gap per iteration")
ax_gap.legend()

plt.tight_layout()
plt.show()
print("Plot saved.")

"""# Problem 1

---

projected subgradient
"""

import cvxpy as cp
import numpy as np
import matplotlib.pyplot as plt
import time

# ── f and gradient ────────────────────────────────────────────────────────────
def f(x):  return x**2
def g(x):  return 2*x

# settings
x_low, x_high = -0.5, 1.0
tolerance     = 0.0001

#initalizing
x_init        = x_low
x = x_init
bestx = x_init
fbest = f(bestx)

#need to fix how I define the bounds here
Upper_bound      = f(x_init)
Lower_bound      = -10000.0

history = []

start_time = time.process_time()
print(f"{'iter':>4} | {'x_k':>8} | {'UB':>10} | {'LB':>12} | {'gap':>12}")
print("-" * 60)
start_time = time.process_time()

# ── projected subgradient ────────────────────────────────────────────────────────
for iteration in range(1, 1000):
    fx = f(x)
    gx = g(x)

    alpha = 1/np.sqrt(iteration)
    x_star = np.clip(x - alpha * gx, x_low, x_high)

    # update best
    if f(x_star) < fbest:
        bestx = x_star
        fbest = f(x_star)

    # bounds
    Upper_bound = fbest

    lb1 = fx + gx * (x_low - x)
    lb2 = fx + gx * (x_high - x)
    LB_k = min(lb1, lb2)
    Lower_bound = max(Lower_bound, LB_k)

    gap = Upper_bound - Lower_bound
    print(f"{iteration:>4} | {x_star:>8.4f} | "
          f"{Upper_bound:>10.4f} | {Lower_bound:>12.4f} | {gap:>12.6f}")


    if gap <= tolerance:
        print(f"\nConverged at iteration {iteration}")
        print(f"Optimal x ≈ {bestx:.6f}, f ≈ {fbest:.6f}")
        break

    x = x_star
    history.append((iteration, x_star, Upper_bound, Lower_bound))
cpu_time = time.process_time() - start_time
print("Time:", cpu_time)
print("\nSummary Table")
print("-" * 65)
print(f"{'f(x*)':>12} | {'gap':>12} | {'iterations':>12} | {'CPU time':>12}")
print("-" * 65)
print(f"{fbest:>12.6f} | {gap:>12.6f} | {iteration:>12} | {cpu_time:>12.6f}")
print("-" * 65)

# ── unpack history ────────────────────────────────────────────────────────────
iters = [h[0] for h in history]
xs    = [h[1] for h in history]
UBs   = [h[2] for h in history]
LBs   = [h[3] for h in history]
gaps  = [u - l for u, l in zip(UBs, LBs)]

# ── figure layout ─────────────────────────────────────────────────────────────
fig, (ax_curve, ax_conv, ax_gap) = plt.subplots(1, 3, figsize=(14, 4))
fig.suptitle("Projected Subgradient — f(x) = x² on [-0.5, 1]")

# ── LEFT: f(x) curve + trajectory ────────────────────────────────────────────
xx = np.linspace(x_low - 0.05, x_high + 0.05, 400)
ax_curve.plot(xx, f(xx), label="f(x) = x²")
ax_curve.scatter(xs, [f(xi) for xi in xs], color="orange", s=10, label="trajectory")
ax_curve.scatter(bestx, fbest, color="red", s=80, zorder=6, label=f"best x={bestx:.4f}")
ax_curve.set_xlabel("x"); ax_curve.set_ylabel("f(x)")
ax_curve.set_title("Subgradient trajectory"); ax_curve.legend()

# ── MIDDLE: UB and LB vs iteration ───────────────────────────────────────────
ax_conv.plot(iters, UBs, marker="o", label="UB_k")
ax_conv.plot(iters, LBs, marker="s", label="LB_k")
ax_conv.set_xlabel("Iteration k"); ax_conv.set_ylabel("Bound value")
ax_conv.set_title("UB and LB per iteration"); ax_conv.legend()

# ── RIGHT: gap vs iteration ───────────────────────────────────────────────────
ax_gap.plot(iters, gaps, marker="o", label="Gap_k = UB_k - LB_k")
ax_gap.axhline(tolerance, linestyle="--", color="red", label=f"ε={tolerance}")
ax_gap.set_xlabel("Iteration k"); ax_gap.set_ylabel("Gap")
ax_gap.set_title("Optimality gap per iteration"); ax_gap.legend()

plt.tight_layout(); plt.show()

"""# Problem 1 Subgradient but with stopping point based on change in x"""

import numpy as np
import matplotlib.pyplot as plt
import time

def f(x):  return x**2
def g(x):  return 2*x

x_low, x_high = -0.5, 1.0
tolerance = 1e-4        # stop when ||x_k - x_{k-1}|| <= this

x      = x_low
bestx  = x
fbest  = f(bestx)
history = []

start_time = time.process_time()
print(f"{'iter':>4} | {'x_k':>8} | {'f(x_k)':>10} | {'f_best':>10} | {'||dx||':>10}")
print("-" * 60)

for iteration in range(1, 1000):
    alpha  = 1 / np.sqrt(iteration)
    gx     = g(x)
    x_new  = np.clip(x - alpha * gx, x_low, x_high)

    # ── stopping criterion: change in x ──────────────────────────────
    dx = np.linalg.norm(x_new - x)   # works for scalar or vector x

    if f(x_new) < fbest:
        bestx = x_new
        fbest = f(x_new)

    print(f"{iteration:>4} | {x_new:>8.4f} | {f(x_new):>10.4f} | {fbest:>10.4f} | {dx:>10.6f}")

    history.append((iteration, x_new, fbest, dx))
    x = x_new

    if dx <= tolerance:
        print(f"\nConverged at iteration {iteration}: ||dx|| = {dx:.6f} <= {tolerance}")
        break

cpu_time = time.process_time() - start_time

print(f"\nOptimal x ≈ {bestx:.6f}, f ≈ {fbest:.6f}")
print("\nSummary")
print("-" * 50)
print(f"{'f(x*)':>12} | {'iterations':>12} | {'CPU time':>12}")
print("-" * 50)
print(f"{fbest:>12.6f} | {iteration:>12} | {cpu_time:>12.6f}")

# ── unpack history ────────────────────────────────────────────────────
iters  = [h[0] for h in history]
xs     = [h[1] for h in history]
fbests = [h[2] for h in history]
dxs    = [h[3] for h in history]

# ── plots ─────────────────────────────────────────────────────────────
fig, (ax_curve, ax_fbest, ax_dx) = plt.subplots(1, 3, figsize=(14, 4))
fig.suptitle("Projected Subgradient — f(x) = x² on [-0.5, 1]")

# f(x) curve + trajectory
xx = np.linspace(x_low - 0.05, x_high + 0.05, 400)
ax_curve.plot(xx, f(xx), label="f(x) = x²")
ax_curve.scatter(xs, [f(xi) for xi in xs], color="orange", s=10, label="trajectory")
ax_curve.scatter(bestx, fbest, color="red", s=80, zorder=6, label=f"best x={bestx:.4f}")
ax_curve.set_xlabel("x"); ax_curve.set_ylabel("f(x)")
ax_curve.set_title("Subgradient trajectory"); ax_curve.legend()

# best f value over iterations
ax_fbest.plot(iters, fbests, marker="o", markersize=3, label="f(x_best)")
ax_fbest.set_xlabel("Iteration k"); ax_fbest.set_ylabel("f(x_best)")
ax_fbest.set_title("Best f value found"); ax_fbest.legend()

# ||dx|| over iterations
ax_dx.plot(iters, dxs, marker="o", markersize=3, color="green", label="||x_k - x_{k-1}||")
ax_dx.axhline(tolerance, linestyle="--", color="red", label=f"tolerance={tolerance}")
ax_dx.set_xlabel("Iteration k"); ax_dx.set_ylabel("||dx||")
ax_dx.set_title("Step change ||dx||"); ax_dx.legend()

plt.tight_layout(); plt.show()

"""# Problem 2

---

cutting plane method
"""

import cvxpy as cp
import numpy as np
import matplotlib.pyplot as plt


# ── f and gradient ────────────────────────────────────────────────────────────
def f(x):  return x**2
def g(x):  return 2*x

# ── settings ──────────────────────────────────────────────────────────────────
x_low, x_high = 1.0, 2.0
tolerance     = 0.0001
x_init        = x_low

constraints_list = [(f(x_init), g(x_init), x_init)]
upper_bound      = f(x_init)
lower_bound      = -10000.0

history = []   # (iter, x_star, theta_star, UB, LB)

print(f"{'Iter':>4} | {'x*':>8} | {'theta*':>10} | {'UB':>10} | {'LB':>12} | {'Gap':>12}")
print("-" * 70)

# ── cutting-plane loop ────────────────────────────────────────────────────────
for iteration in range(1, 1000):
    x     = cp.Variable()
    theta = cp.Variable()

    cvxpy_constraints = [x >= x_low, x <= x_high]
    for (fi, gi, xi) in constraints_list:
        cvxpy_constraints.append(theta >= fi + gi * (x - xi))

    prob = cp.Problem(cp.Minimize(theta), cvxpy_constraints)
    prob.solve(solver=cp.HIGHS)

    x_star     = x.value
    theta_star = theta.value

    lower_bound = theta_star
    upper_bound = min(upper_bound, f(x_star))
    gap         = upper_bound - lower_bound

    history.append((iteration, x_star, theta_star, upper_bound, lower_bound))
    print(f"{iteration:>4} | {x_star:>8.4f} | {theta_star:>10.4f} | "
          f"{upper_bound:>10.4f} | {lower_bound:>12.4f} | {gap:>12.6f}")

    if gap <= tolerance:
        print(f"\nConverged at iteration {iteration}!")
        print(f"Optimal x  ≈ {x_star:.6f}")
        print(f"Optimal f  ≈ {f(x_star):.6f}")
        break

    constraints_list.append((f(x_star), g(x_star), x_star))

# ── unpack history ────────────────────────────────────────────────────────────
iters  = [h[0] for h in history]
xs     = [h[1] for h in history]
UBs    = [h[3] for h in history]
LBs    = [h[4] for h in history]
gaps   = [u - l for u, l in zip(UBs, LBs)]

# ── figure layout ─────────────────────────────────────────────────────────────
fig, (ax_curve, ax_conv, ax_gap) = plt.subplots(1, 3, figsize=(14, 4))
fig.suptitle("Cutting Plane Method — f(x) = x^2 on [1, 2]")

# ── LEFT: f(x) curve + trial points ──────────────────────────────────────────
xx = np.linspace(x_low - 0.05, x_high + 0.05, 400)

ax_curve.plot(xx, f(xx), label="f(x) = x^2")

# draw cutting planes
for (fi, gi, xi) in constraints_list:
    ax_curve.plot(xx, fi + gi * (xx - xi), color="gray", linewidth=0.8, alpha=0.6)

# trial points
ax_curve.scatter(xs, [f(x) for x in xs], color="orange", zorder=5, label="Trial points")
ax_curve.scatter(xs[-1], f(xs[-1]), color="red", zorder=6, s=80, label=f"Optimal x*={xs[-1]:.4f}")

ax_curve.set_xlabel("x")
ax_curve.set_ylabel("f(x)")
ax_curve.set_title("f(x) with cutting planes")
ax_curve.legend()

# ── MIDDLE: UB and LB vs iteration ───────────────────────────────────────────
ax_conv.plot(iters, UBs, marker="o", label="UB_k")
ax_conv.plot(iters, LBs, marker="s", label="LB_k")

ax_conv.set_xlabel("Iteration k")
ax_conv.set_ylabel("Bound value")
ax_conv.set_title("UB and LB per iteration")
ax_conv.legend()

# ── RIGHT: gap vs iteration ───────────────────────────────────────────────────
ax_gap.plot(iters, gaps, marker="o", label="Gap_k = UB_k - LB_k")
ax_gap.axhline(tolerance, linestyle="--", color="red", label=f"Tolerance = {tolerance}")

ax_gap.set_xlabel("Iteration k")
ax_gap.set_ylabel("Gap")
ax_gap.set_title("Optimality gap per iteration")
ax_gap.legend()

plt.tight_layout()
plt.show()
print("Plot saved.")

"""# Problem 2


---
projected subgradient



"""



import cvxpy as cp
import numpy as np
import matplotlib.pyplot as plt

# ── f and gradient ────────────────────────────────────────────────────────────
def f(x):  return x**2
def g(x):  return 2*x

# ── settings ──────────────────────────────────────────────────────────────────
x_low, x_high = 1, 2
tolerance     = 0.0001
x_init        = x_low

#initalizing
x = x_init
bestx = x_init
fbest = f(bestx)

#need to fix how I define the bounds here
Upper_bound      = f(x_init)
Lower_bound      = -10000.0

history = []

start_time = time.process_time()
print(f"{'iter':>4} | {'x_k':>8} | {'UB':>10} | {'LB':>12} | {'gap':>12}")
print("-" * 60)

# ── projected subgradient ────────────────────────────────────────────────────────
for iteration in range(1, 1000):
    fx = f(x)
    gx = g(x)
    alpha = 1/np.sqrt(iteration)
    x_star = np.clip(x - alpha * g(x), x_low, x_high)
    fx= f(x_star)
    print(f"{iteration:>4} | {x_star:>8.4f}")

    if fx < fbest:
        bestx = x_star
        fbest = fx

    Upper_bound  = fbest
    lb1 = fx + gx * (x_low - x)
    lb2 = fx + gx * (x_high - x)
    LB_k = min(lb1, lb2)
    Lower_bound = max(Lower_bound, LB_k)

    gap = Upper_bound - Lower_bound
    print(f"{iteration:>4} | {x_star:>8.4f} | "
          f"{Upper_bound:>10.4f} | {Lower_bound:>12.4f} | {gap:>12.6f}")

    if gap <= tolerance:
        print(f"Converged at iteration {iteration}")
        print(f"Optimal x ≈ {bestx:.6f}, f ≈ {fbest:.6f}")
        break
    x = x_star
    history.append((iteration, x_star, Upper_bound, Lower_bound))
cpu_time = time.process_time() - start_time
print("\nSummary Table")
print("-" * 65)
print(f"{'f(x*)':>12} | {'gap':>12} | {'iterations':>12} | {'CPU time':>12}")
print("-" * 65)
print(f"{fbest:>12.6f} | {gap:>12.6f} | {iteration:>12} | {cpu_time:>12.6f}")
print("-" * 65)

# ── unpack history ────────────────────────────────────────────────────────────
iters = [h[0] for h in history]
xs    = [h[1] for h in history]
UBs   = [h[2] for h in history]
LBs   = [h[3] for h in history]
gaps  = [u - l for u, l in zip(UBs, LBs)]

# ── figure layout ─────────────────────────────────────────────────────────────
fig, (ax_curve, ax_conv, ax_gap) = plt.subplots(1, 3, figsize=(14, 4))
fig.suptitle("Projected Subgradient — f(x) = x² on [-0.5, 1]")

# ── LEFT: f(x) curve + trajectory ────────────────────────────────────────────
xx = np.linspace(x_low - 0.05, x_high + 0.05, 400)
ax_curve.plot(xx, f(xx), label="f(x) = x²")
ax_curve.scatter(xs, [f(xi) for xi in xs], color="orange", s=10, label="trajectory")
ax_curve.scatter(bestx, fbest, color="red", s=80, zorder=6, label=f"best x={bestx:.4f}")
ax_curve.set_xlabel("x"); ax_curve.set_ylabel("f(x)")
ax_curve.set_title("Subgradient trajectory"); ax_curve.legend()

# ── MIDDLE: UB and LB vs iteration ───────────────────────────────────────────
ax_conv.plot(iters, UBs, marker="o", label="UB_k")
ax_conv.plot(iters, LBs, marker="s", label="LB_k")

ax_conv.set_xlabel("Iteration k")
ax_conv.set_ylabel("Bound value")
ax_conv.set_title("UB and LB per iteration")
ax_conv.legend()

# ── RIGHT: gap vs iteration ───────────────────────────────────────────────────
ax_gap.plot(iters, gaps, marker="o", label="Gap_k = UB_k - LB_k")
ax_gap.axhline(tolerance, linestyle="--", color="red", label=f"Tolerance = {tolerance}")

ax_gap.set_xlabel("Iteration k")
ax_gap.set_ylabel("Gap")
ax_gap.set_title("Optimality gap per iteration")
ax_gap.legend()

plt.tight_layout(); plt.show()

import numpy as np
import matplotlib.pyplot as plt
import time

def f(x):  return x**2
def g(x):  return 2*x

x_low, x_high = 1.0, 2.0
tolerance = 1e-4        # stop when ||x_k - x_{k-1}|| <= this

x      = x_low
bestx  = x
fbest  = f(bestx)
history = []

start_time = time.process_time()
print(f"{'iter':>4} | {'x_k':>8} | {'f(x_k)':>10} | {'f_best':>10} | {'||dx||':>10}")
print("-" * 60)

for iteration in range(1, 1000):
    alpha  = 1 / np.sqrt(iteration)
    gx     = g(x)
    x_new  = np.clip(x - alpha * gx, x_low, x_high)

    # ── stopping criterion: change in x ──────────────────────────────
    dx = np.linalg.norm(x_new - x)   # works for scalar or vector x

    if f(x_new) < fbest:
        bestx = x_new
        fbest = f(x_new)

    print(f"{iteration:>4} | {x_new:>8.4f} | {f(x_new):>10.4f} | {fbest:>10.4f} | {dx:>10.6f}")

    history.append((iteration, x_new, fbest, dx))
    x = x_new

    if dx <= tolerance:
        print(f"\nConverged at iteration {iteration}: ||dx|| = {dx:.6f} <= {tolerance}")
        break

cpu_time = time.process_time() - start_time

print(f"\nOptimal x ≈ {bestx:.6f}, f ≈ {fbest:.6f}")
print("\nSummary")
print("-" * 50)
print(f"{'f(x*)':>12} | {'iterations':>12} | {'CPU time':>12}")
print("-" * 50)
print(f"{fbest:>12.6f} | {iteration:>12} | {cpu_time:>12.6f}")

# ── unpack history ────────────────────────────────────────────────────
iters  = [h[0] for h in history]
xs     = [h[1] for h in history]
fbests = [h[2] for h in history]
dxs    = [h[3] for h in history]

# ── plots ─────────────────────────────────────────────────────────────
fig, (ax_curve, ax_fbest, ax_dx) = plt.subplots(1, 3, figsize=(14, 4))
fig.suptitle("Projected Subgradient — f(x) = x² on [1,2]")

# f(x) curve + trajectory
xx = np.linspace(x_low - 0.05, x_high + 0.05, 400)
ax_curve.plot(xx, f(xx), label="f(x) = x²")
ax_curve.scatter(xs, [f(xi) for xi in xs], color="orange", s=10, label="trajectory")
ax_curve.scatter(bestx, fbest, color="red", s=80, zorder=6, label=f"best x={bestx:.4f}")
ax_curve.set_xlabel("x"); ax_curve.set_ylabel("f(x)")
ax_curve.set_title("Subgradient trajectory"); ax_curve.legend()

# best f value over iterations
ax_fbest.plot(iters, fbests, marker="o", markersize=3, label="f(x_best)")
ax_fbest.set_xlabel("Iteration k"); ax_fbest.set_ylabel("f(x_best)")
ax_fbest.set_title("Best f value found"); ax_fbest.legend()

# ||dx|| over iterations
ax_dx.plot(iters, dxs, marker="o", markersize=3, color="green", label="||x_k - x_{k-1}||")
ax_dx.axhline(tolerance, linestyle="--", color="red", label=f"tolerance={tolerance}")
ax_dx.set_xlabel("Iteration k"); ax_dx.set_ylabel("||dx||")
ax_dx.set_title("Step change ||dx||"); ax_dx.legend()

plt.tight_layout(); plt.show()

"""# Problem 3
Note: How do you do the gradiant of the max of three functions?
"""

import cvxpy as cp
import numpy as np
import matplotlib.pyplot as plt
from scipy.optimize import fsolve

start_time = time.process_time()

#Defining the functions
xp = np.linspace(-0.5,2,50)
def f1(x): return np.exp(-x)
def f2(x): return x
def f3(x): return x**2
def f(x):
    return np.maximum.reduce([f1(x), f2(x), f3(x)])
fxp= np.maximum.reduce([f1(xp), f2(xp), f3(xp)])

#the gradients
def g1(x): return -1*np.exp(-x)
def g2(_x): return 1
def g3(x): return 2*x

def subgrads(x):
    fx = [f1(x), f2(x), f3(x)]
    gx = [g1(x), g2(x), g3(x)]
    return gx[int(np.argmax(fx))]

#plot of the original function
plt.plot(xp,fxp)
plt.show()

# settings
x_low, x_high = -0.5, 2
tolerance = 0.0001
x_init = x_low
history = []
constraints_list = [(f(x_init), subgrads(x_init), x_init)]
upper_bound      = f(x_init)
lower_bound      = -10000.0

#cutting plane loop
for iteration in range (1, 1000):
  x = cp.Variable()
  theta = cp.Variable()
  constraints= [x >=x_low, x<=x_high]
  for (fi, gi, xi) in constraints_list:
    constraints.append(theta>=fi+gi*(x-xi))
  prob = cp.Problem(cp.Minimize(theta), constraints)
  prob.solve(solver=cp.HIGHS)
  x_star=x.value
  theta_star=theta.value

  lower_bound= theta_star
  upper_bound= min(upper_bound, f(x_star))
  gap = upper_bound-lower_bound

  history.append((iteration, x_star, theta_star, upper_bound, lower_bound))

  if gap <= tolerance:
      print(f"\nConverged at iteration {iteration}!")
      print(f"Optimal x  ≈ {x_star:.6f}")
      print(f"Optimal f  ≈ {f(x_star):.6f}")
      break

  constraints_list.append((f(x_star), subgrads(x_star), x_star))
cpu_time = time.process_time() - start_time
print("cpu_time:", cpu_time)
# ── unpack history ────────────────────────────────────────────────────────────
iters  = [h[0] for h in history]
xs     = [h[1] for h in history]
UBs    = [h[3] for h in history]
LBs    = [h[4] for h in history]
gaps   = [u - l for u, l in zip(UBs, LBs)]
print("Gaps:", gaps)
# ── figure layout ─────────────────────────────────────────────────────────────
fig, (ax_curve, ax_conv, ax_gap) = plt.subplots(1, 3, figsize=(14, 4))
fig.suptitle("Cutting Plane Method — f(x) = x^2 on [1, 2]")

# ── LEFT: f(x) curve + trial points ──────────────────────────────────────────
xx = np.linspace(x_low - 0.05, x_high + 0.05, 400)

ax_curve.plot(xx, f(xx), label="f(x) = x^2")

# draw cutting planes
for (fi, gi, xi) in constraints_list:
    ax_curve.plot(xx, fi + gi * (xx - xi), color="gray", linewidth=0.8, alpha=0.6)

# trial points
ax_curve.scatter(xs, [f(x) for x in xs], color="orange", zorder=5, label="Trial points")
ax_curve.scatter(xs[-1], f(xs[-1]), color="red", zorder=6, s=80, label=f"Optimal x*={xs[-1]:.4f}")

ax_curve.set_xlabel("x")
ax_curve.set_ylabel("f(x)")
ax_curve.set_title("f(x) with cutting planes")
ax_curve.legend()

# ── MIDDLE: UB and LB vs iteration ───────────────────────────────────────────
ax_conv.plot(iters, UBs, marker="o", label="UB_k")
ax_conv.plot(iters, LBs, marker="s", label="LB_k")

ax_conv.set_xlabel("Iteration k")
ax_conv.set_ylabel("Bound value")
ax_conv.set_title("UB and LB per iteration")
ax_conv.legend()

# ── RIGHT: gap vs iteration ───────────────────────────────────────────────────
ax_gap.plot(iters, gaps, marker="o", label="Gap_k = UB_k - LB_k")
ax_gap.axhline(tolerance, linestyle="--", color="red", label=f"Tolerance = {tolerance}")

ax_gap.set_xlabel("Iteration k")
ax_gap.set_ylabel("Gap")
ax_gap.set_title("Optimality gap per iteration")
ax_gap.legend()

plt.tight_layout()
plt.show()
print("Plot saved.")

"""# Problem 3

---

projected subgradient: Unsure if I've bounded this correctly
"""

#Defining the functions
xp = np.linspace(-0.5,2,50)
def f1(x): return np.exp(-x)
def f2(x): return x
def f3(x): return x**2
def f(x):
    return np.maximum.reduce([f1(x), f2(x), f3(x)])
fxp= np.maximum.reduce([f1(xp), f2(xp), f3(xp)])

#the gradients
def g1(x): return -1*np.exp(-x)
def g2(_x): return 1
def g3(x): return 2*x

def subgrads(x):
    fx = [f1(x), f2(x), f3(x)]
    gx = [g1(x), g2(x), g3(x)]
    return gx[int(np.argmax(fx))]

# ── settings ──────────────────────────────────────────────────────────────────
x_low, x_high = -0.5, 2
tolerance     = 0.0001
x_init        = x_low

#initalizing
x = x_init
bestx = x_init
fbest = f(bestx)

#need to fix how I define the bounds here
Upper_bound      = f(x_init)
Lower_bound      = -10000.0

history = []
start_time = time.process_time()

# ── projected subgradient ────────────────────────────────────────────────────────
for iteration in range(1, 1000000):
    fx = f(x)
    gx = subgrads(x)
    alpha = 1 / np.sqrt(iteration)
    x_star = np.clip(x - alpha * gx, x_low, x_high)

    if f(x_star) < fbest:
        bestx = x_star
        fbest = f(x_star)

    Upper_bound = fbest
    lb1 = fx + gx * (x_low - x)
    lb2 = fx + gx * (x_high - x)
    LB_k = min(lb1, lb2)
    Lower_bound = max(Lower_bound, LB_k)

    gap = Upper_bound - Lower_bound   # ← recompute gap every iteration

    if gap <= tolerance:
        print(f"Converged at iteration {iteration}")
        print(f"Optimal x ≈ {bestx:.6f}, f ≈ {fbest:.6f}")
        break

    x = x_star
    history.append((iteration, x_star, Upper_bound, Lower_bound))

cpu_time = time.process_time() - start_time
print("Time:", cpu_time)
print(f"\n{'='*45}")
print(f"{'SUMMARY':^45}")
print(f"{'='*45}")
print(f"{'Final f(x*)':.<30} {fbest:.6f}")
print(f"{'Final gap':.<30} {gap:.6f}")
print(f"{'Total iterations':.<30} {iteration}")
print(f"{'CPU time (s)':.<30} {cpu_time:.4f}")
print(f"{'='*45}")
# ── unpack history ────────────────────────────────────────────────────────────
iters = [h[0] for h in history]
xs    = [h[1] for h in history]
UBs   = [h[2] for h in history]
LBs   = [h[3] for h in history]
gaps  = [u - l for u, l in zip(UBs, LBs)]
#print("Gaps", gaps)
# ── figure layout ─────────────────────────────────────────────────────────────
fig, (ax_curve, ax_conv, ax_gap) = plt.subplots(1, 3, figsize=(14, 4))
fig.suptitle("Projected Subgradient — f(x) = x² on [-0.5, 1]")

# ── LEFT: f(x) curve + trajectory ────────────────────────────────────────────
xx = np.linspace(x_low - 0.05, x_high + 0.05, 400)
ax_curve.plot(xx, f(xx), label="f(x) = x²")
ax_curve.scatter(xs, [f(xi) for xi in xs], color="orange", s=10, label="trajectory")
ax_curve.scatter(bestx, fbest, color="red", s=80, zorder=6, label=f"best x={bestx:.4f}")
ax_curve.set_xlabel("x"); ax_curve.set_ylabel("f(x)")
ax_curve.set_title("Subgradient trajectory"); ax_curve.legend()

# ── MIDDLE: UB and LB vs iteration ───────────────────────────────────────────
ax_conv.plot(iters, UBs, marker="o", label="UB_k")
ax_conv.plot(iters, LBs, marker="s", label="LB_k")

ax_conv.set_xlabel("Iteration k")
ax_conv.set_ylabel("Bound value")
ax_conv.set_title("UB and LB per iteration")
ax_conv.legend()

# ── RIGHT: gap vs iteration ───────────────────────────────────────────────────
ax_gap.plot(iters, gaps, marker="o", label="Gap_k = UB_k - LB_k")
ax_gap.axhline(tolerance, linestyle="--", color="red", label=f"Tolerance = {tolerance}")

ax_gap.set_xlabel("Iteration k")
ax_gap.set_ylabel("Gap")
ax_gap.set_title("Optimality gap per iteration")
ax_gap.legend()

plt.tight_layout(); plt.show()

"""# Problem 3 with new subgradient"""

import numpy as np
import matplotlib.pyplot as plt
import time

# ── functions and subgradient ─────────────────────────────────────────────────
def f1(x): return np.exp(-x)
def f2(x): return x
def f3(x): return x**2

def f(x):
    return np.maximum.reduce([f1(x), f2(x), f3(x)])

def g(x):
    fx = [f1(x), f2(x), f3(x)]
    gx = [g1(x), g2(x), g3(x)]
    return gx[int(np.argmax(fx))]

def g1(x): return -1 * np.exp(-x)
def g2(_x): return 1
def g3(x): return 2 * x

# ── settings ──────────────────────────────────────────────────────────────────
x_low, x_high = -0.5, 2.0
tolerance = 1e-2

x     = x_low
bestx = x
fbest = f(bestx)
history = []

start_time = time.process_time()
print(f"{'iter':>4} | {'x_k':>8} | {'f(x_k)':>10} | {'f_best':>10} | {'||dx||':>10}")
print("-" * 60)

# ── projected subgradient loop ────────────────────────────────────────────────
for iteration in range(1, 10000):
    alpha = 1 / np.sqrt(iteration)
    gx    = g(x)
    x_new = np.clip(x - alpha * gx, x_low, x_high)

    # stopping criterion: change in x
    dx = np.linalg.norm(x_new - x)

    if f(x_new) < fbest:
        bestx = x_new
        fbest = f(x_new)

    #print(f"{iteration:>4} | {x_new:>8.4f} | {f(x_new):>10.4f} | {fbest:>10.4f} | {dx:>10.6f}")

    history.append((iteration, x_new, fbest, dx))
    x = x_new

    if dx <= tolerance:
        print(f"\nConverged at iteration {iteration}: ||dx|| = {dx:.6f} <= {tolerance}")
        break

cpu_time = time.process_time() - start_time

print(f"\nOptimal x ≈ {bestx:.6f}, f ≈ {fbest:.6f}")
print("\nSummary")
print("-" * 50)
print(f"{'f(x*)':>12} | {'iterations':>12} | {'CPU time':>12}")
print("-" * 50)
print(f"{fbest:>12.6f} | {iteration:>12} | {cpu_time:>12.6f}")

# ── unpack history ────────────────────────────────────────────────────────────
iters  = [h[0] for h in history]
xs     = [h[1] for h in history]
fbests = [h[2] for h in history]
dxs    = [h[3] for h in history]

# ── plots ─────────────────────────────────────────────────────────────────────
fig, (ax_curve, ax_fbest, ax_dx) = plt.subplots(1, 3, figsize=(14, 4))
fig.suptitle("Projected Subgradient — f(x) = max(e^-x, x, x²) on [-0.5, 2]")

# f(x) curve + individual functions + trajectory
xx = np.linspace(x_low - 0.05, x_high + 0.05, 400)
ax_curve.plot(xx, f(xx),  label="f(x) = max(...)", linewidth=2)
ax_curve.plot(xx, f1(xx), label="e^-x",  linestyle="--", alpha=0.5)
ax_curve.plot(xx, f2(xx), label="x",     linestyle="--", alpha=0.5)
ax_curve.plot(xx, f3(xx), label="x²",    linestyle="--", alpha=0.5)
ax_curve.scatter(xs, [f(xi) for xi in xs], color="orange", s=10, label="trajectory")
ax_curve.scatter(bestx, fbest, color="red", s=80, zorder=6, label=f"best x={bestx:.4f}")
ax_curve.set_xlabel("x"); ax_curve.set_ylabel("f(x)")
ax_curve.set_title("Subgradient trajectory"); ax_curve.legend(fontsize=7)

# best f value over iterations
ax_fbest.plot(iters, fbests, marker="o", markersize=3, label="f(x_best)")
ax_fbest.set_xlabel("Iteration k"); ax_fbest.set_ylabel("f(x_best)")
ax_fbest.set_title("Best f value found"); ax_fbest.legend()

# ||dx|| over iterations
ax_dx.plot(iters, dxs, marker="o", markersize=3, color="green", label="||x_k - x_{k-1}||")
ax_dx.axhline(tolerance, linestyle="--", color="red", label=f"tolerance={tolerance}")
ax_dx.set_xlabel("Iteration k"); ax_dx.set_ylabel("||dx||")
ax_dx.set_title("Step change ||dx||"); ax_dx.legend()

plt.tight_layout()
plt.show()

"""## Problem 4

Solved, but for n=100 and n=500 it takes too much time to run with lower processing power so I cut it off at 30 seconds of run time. For this reason, the plots for those higher dimensions are slightly skewed. This is largely due to the fact that too many cuts have to be made for a function of that many dimensions for convergence to happen in a timely manner.
"""

import cvxpy as cp
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import time

# define f and g
def f(x):
    return np.dot(x, x)

def g(x):
    return 2 * x

dimensions = [2, 5, 10, 100, 500]
results = []
historysALL = {}

#algorithm
for n in dimensions:
    print(f"Running n = {n}...")
    start = time.time()

    x_low = -0.5 * np.ones(n)
    x_high = np.ones(n)
    tolerance = 0.0001

    x_init = x_low.copy()

    UB_hist, LB_hist, gap_hist = [], [], []

    constraints_list = [(f(x_init), g(x_init), x_init)]
    best_UB = f(x_init)

    #loop for the cuts
    for k in range(1, 1000):
        if k%100==0:
          print(k)
        # CVXPY Setup
        x = cp.Variable(n)
        theta = cp.Variable()

        #constraints for the bounds
        constraints = [x >= x_low, x <= x_high]

        #add the histroical cuts
        for (fi, gi, xi) in constraints_list:
            constraints.append(theta >= fi + gi @ (x - xi))

        prob = cp.Problem(cp.Minimize(theta), constraints)
        prob.solve(solver=cp.HIGHS)

        x_star = x.value
        best_LB = theta.value

        #update bounds
        best_UB = min(best_UB, f(x_star))
        gap = best_UB - best_LB

        UB_hist.append(best_UB)
        LB_hist.append(best_LB)
        gap_hist.append(gap)

        #check for convergence
        if gap <= tolerance:
            print(f"  -> Converged at iteration {k}!")
            break

        #time out at 30 seconds
        # if time.time() - start > 30.0:
        #     print(f"  -> [TIMEOUT] n={n} hit the 30-second limit at iteration {k}.")
        #     break

        #updated cut for the loop
        constraints_list.append((f(x_star), g(x_star), x_star))

    elapsed = time.time() - start
    historysALL[n] = {'UB': UB_hist, 'LB': LB_hist, 'Gap': gap_hist}
    results.append({'n': n, 'Method': 'Kelley', 'f(x*)': best_UB, 'Final Gap': gap, 'Iterations': k, 'CPU Time (s)': elapsed})

#summary
df = pd.DataFrame(results)
pd.set_option('display.float_format', lambda x: '%.6f' % x)
print("\n=== Kelley's Method Summary (Problem 4) ===")
print(df.to_string(index=False))


#plots
fig1, axes = plt.subplots(1, len(dimensions), figsize=(20, 4))
fig1.suptitle("Kelley's Method Convergence (UB, LB, Gap) - Problem 4", fontsize=16)

for idx, n in enumerate(dimensions):
    ax = axes[idx]
    hist = historysALL[n]
    ax.plot(hist['Gap'], label='Gap (UB - LB)', color='green', linewidth=2)
    ax.plot(hist['UB'], label='UB', color='blue', linestyle='--')
    ax.plot(hist['LB'], label='LB', color='red', linestyle='--')
    ax.axhline(tolerance, color='black', linestyle=':', label='Tol (0.0004)')
    ax.set_title(f"Dimension n={n}")
    ax.set_xlabel("Iteration k")
    ax.set_yscale('symlog')
    if idx == 0: ax.legend()

plt.tight_layout()
plt.subplots_adjust(top=0.85)
plt.show()

fig2, (ax_iter, ax_time) = plt.subplots(1, 2, figsize=(14, 5))

ns = [r['n'] for r in results]
iters = [r['Iterations'] for r in results]
times = [r['CPU Time (s)'] for r in results]

#Iterations vs n
ax_iter.plot(ns, iters, marker="o", color="blue")
ax_iter.set_xscale('log')
ax_iter.set_xticks(ns)
ax_iter.set_xticklabels(ns)
ax_iter.set_title("Total Iterations vs Dimension (n)")
ax_iter.set_xlabel("Dimension (n) - Log Scale")
ax_iter.set_ylabel("Iterations")

#CPU time vs n
ax_time.plot(ns, times, marker="o", color="orange")
ax_time.set_xscale('log')
ax_time.set_xticks(ns)
ax_time.set_xticklabels(ns)
ax_time.set_title("CPU Time vs Dimension (n)")
ax_time.set_xlabel("Dimension (n) - Log Scale")
ax_time.set_ylabel("Time (seconds)")

plt.tight_layout()
plt.show()

#summary
df = pd.DataFrame(results)
pd.set_option('display.float_format', lambda x: '%.6f' % x)
print("\n=== Kelley's Method Summary (Problem 4) ===")
print(df.to_string(index=False))


#plots
fig1, axes = plt.subplots(1, len(dimensions), figsize=(20, 4))
fig1.suptitle("Kelley's Method Convergence (UB, LB, Gap) - Problem 4", fontsize=16)

for idx, n in enumerate(dimensions):
    ax = axes[idx]
    hist = historysALL[n]
    ax.plot(hist['Gap'], label='Gap (UB - LB)', color='green', linewidth=2)
    ax.plot(hist['UB'], label='UB', color='blue', linestyle='--')
    ax.plot(hist['LB'], label='LB', color='red', linestyle='--')
    ax.axhline(tolerance, color='black', linestyle=':', label='Tol (0.0001)')
    ax.set_title(f"Dimension n={n}")
    ax.set_xlabel("Iteration k")
    ax.set_yscale('symlog')
    if idx == 0: ax.legend()

plt.tight_layout()
plt.subplots_adjust(top=0.85)
plt.show()

fig2, (ax_iter, ax_time) = plt.subplots(1, 2, figsize=(14, 5))

ns = [r['n'] for r in results]
iters = [r['Iterations'] for r in results]
times = [r['CPU Time (s)'] for r in results]

#Iterations vs n
ax_iter.plot(ns, iters, marker="o", color="blue")
ax_iter.set_xscale('log')
ax_iter.set_xticks(ns)
ax_iter.set_xticklabels(ns)
ax_iter.set_title("Total Iterations vs Dimension (n)")
ax_iter.set_xlabel("Dimension (n) - Log Scale")
ax_iter.set_ylabel("Iterations")

#CPU time vs n
ax_time.plot(ns, times, marker="o", color="orange")
ax_time.set_xscale('log')
ax_time.set_xticks(ns)
ax_time.set_xticklabels(ns)
ax_time.set_title("CPU Time vs Dimension (n)")
ax_time.set_xlabel("Dimension (n) - Log Scale")
ax_time.set_ylabel("Time (seconds)")

plt.tight_layout()
plt.show()

"""# Problem 4 Using the "Level Set" Method"""

import cvxpy as cp
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import time

def f(x):   return np.dot(x, x)
def g(x):   return 2 * x

dimensions  = [2, 5, 10, 100, 500]
results     = []
historysALL = {}
lam         = 0.01    # level parameter: 0=stay near UB, 1=push toward LB
tolerance   = 0.0001

for n in dimensions:
    print(f"\nRunning n = {n}...")
    x_low  = -1.0 * np.ones(n)
    x_high =  0.5 * np.ones(n)

    # ── start at corner, far from optimum ────────────────────────────
    x_cur   = x_low.copy()
    best_UB = f(x_cur)
    best_LB = -np.inf
    best_x  = x_cur.copy()

    cuts = [(f(x_cur), g(x_cur), x_cur.copy())]
    UB_hist, LB_hist, gap_hist = [], [], []

    start = time.time()

    for k in range(1, 1000):

        # ── Step 1: LP to update LB ───────────────────────────────────
        x_var  = cp.Variable(n)
        theta  = cp.Variable()
        lp_cons = [x_var >= x_low, x_var <= x_high]
        for (fi, gi, xi) in cuts:
            lp_cons.append(theta >= fi + gi @ (x_var - xi))

        cp.Problem(cp.Minimize(theta), lp_cons).solve(solver=cp.HIGHS)
        best_LB = max(best_LB, theta.value)

        gap = best_UB - best_LB
        UB_hist.append(best_UB)
        LB_hist.append(best_LB)
        gap_hist.append(gap)

        if k % 100 == 0:
            print(f"  k={k:4d} | UB={best_UB:.6f} | LB={best_LB:.6f} | gap={gap:.6f}")

        if gap <= tolerance:
            print(f"  -> Converged at iteration {k}!")
            break

        # ── Step 2: compute level ─────────────────────────────────────
        level = lam * best_LB + (1 - lam) * best_UB

        # ── Step 3: project onto level set ───────────────────────────
        x_var2    = cp.Variable(n)
        proj_cons = [x_var2 >= x_low, x_var2 <= x_high]
        for (fi, gi, xi) in cuts:
            proj_cons.append(fi + gi @ (x_var2 - xi) <= level)

        proj_prob = cp.Problem(cp.Minimize(cp.sum_squares(x_var2 - best_x)), proj_cons)
        proj_prob.solve(solver=cp.HIGHS)

        if proj_prob.status not in ("optimal", "optimal_inaccurate") or x_var2.value is None:
            print(f"  -> Projection infeasible at k={k}, stopping.")
            break

        x_cur = x_var2.value

        # ── update UB from the new projected point ────────────────────
        fx_cur = f(x_cur)
        if fx_cur < best_UB:
            best_UB = fx_cur
            best_x  = x_cur.copy()

        # add new cut at projected point
        cuts.append((f(x_cur), g(x_cur), x_cur.copy()))

    elapsed = time.time() - start
    historysALL[n] = {'UB': UB_hist, 'LB': LB_hist, 'Gap': gap_hist}
    results.append({
        'n': n, 'f(x*)': best_UB, 'Final Gap': gap,
        'Iterations': k, 'CPU Time (s)': elapsed
    })

# ── summary table ─────────────────────────────────────────────────────────────
df = pd.DataFrame(results)
pd.set_option('display.float_format', lambda x: '%.6f' % x)
print("\n=== Level Method Summary (Problem 4) ===")
print(df.to_string(index=False))

# ── convergence plots ─────────────────────────────────────────────────────────
fig1, axes = plt.subplots(1, len(dimensions), figsize=(20, 4))
fig1.suptitle("Level Method Convergence (UB, LB, Gap) — f(x)=||x||² on [-0.5,1]ⁿ")

for idx, n in enumerate(dimensions):
    ax   = axes[idx]
    hist = historysALL[n]
    ax.plot(hist['Gap'], color='green',   linewidth=2,    label='Gap')
    ax.plot(hist['UB'],  color='blue',    linestyle='--', label='UB')
    ax.plot(hist['LB'],  color='red',     linestyle='--', label='LB')
    ax.axhline(tolerance, color='black',  linestyle=':',  label='Tol')
    ax.set_title(f"n = {n}")
    ax.set_xlabel("Iteration k")
    ax.set_yscale('symlog')
    if idx == 0: ax.legend()

plt.tight_layout()
plt.show()

# ── scaling plots ─────────────────────────────────────────────────────────────
fig2, (ax_iter, ax_time) = plt.subplots(1, 2, figsize=(12, 4))
ns    = [r['n'] for r in results]
iters = [r['Iterations'] for r in results]
times = [r['CPU Time (s)'] for r in results]

ax_iter.plot(ns, iters, marker='o')
ax_iter.set_xscale('log'); ax_iter.set_xticks(ns); ax_iter.set_xticklabels(ns)
ax_iter.set_title("Iterations vs n"); ax_iter.set_xlabel("n"); ax_iter.set_ylabel("Iterations")

ax_time.plot(ns, times, marker='o', color='orange')
ax_time.set_xscale('log'); ax_time.set_xticks(ns); ax_time.set_xticklabels(ns)
ax_time.set_title("CPU Time vs n"); ax_time.set_xlabel("n"); ax_time.set_ylabel("Time (s)")

plt.tight_layout()
plt.show()

"""# Problem 4

---
Projected Subgradient

I have plotted the projected subgradient method described in the problem with the plots detailed below.

Explanation:

In the projected subgradient method, there is no solving for unknowns, no matrix inversions, and no system of equations so the number of iterations does not affect the time to run very much because it is just performing x - alpha*g over and over again. Thus, the CPU time scales linearly with the number of iterations and the CPU time per step is pretty linear. However, by increasing the number of dimensions, the number of iterations greatly increases because you are then having to take many more incremental step sizes to get to the true minimum.
"""

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import time

# Define the function that finds f and g,
def oracle_squared_L2(x):
    """Returns f(x) = sum(x^2) and the exact gradient g(x) = 2x"""
    f_val = np.sum(x**2)
    g_val = 2.0 * x
    return f_val, g_val

def run_subgradient(n, x_low=-0.5, x_high=1.0, tol=1e-4, max_iter=5000):
    x = np.full(n, x_high) # Began at the upper bound
    #chose the upper bound because By starting at the upper bound, we are choosing the "worst-case" scenario
    #This will make the alogirthm travel a further distance
    #choosing the lower bound would arrive a tthe same result, only tolerance matters here
    #This is a form of stress testing by choosing the worst case scenario

    best_UB = float('inf')
    best_LB = float('-inf')

    UB_hist, LB_hist, gap_hist = [], [], []

    start_time = time.time()

    for k in range(1, max_iter + 1):
        f_val, g_val = oracle_squared_L2(x)

        # continously update the upper bound
        best_UB = min(best_UB, f_val)

        # calculate LB for the current tangent line
        x_extreme = np.where(g_val > 0, x_low, x_high)
        cut_min = f_val + np.dot(g_val, (x_extreme - x))
        best_LB = max(best_LB, cut_min)

        gap = best_UB - best_LB

        UB_hist.append(best_UB)
        LB_hist.append(best_LB)
        gap_hist.append(gap)

        # End if the optimality gap is reached
        if gap <= tol:
            break

        # subgradient step of 0.1 and projection
        #changing step size to a much bigger number like 1 could make it bounce back and forth
        #Step size less than 0.1 might be too small and take too many iterations to converge
        #We chose a step size that makes the most sense for our given range
        step_size = 0.1 / np.sqrt(k)  # traditional step size used in many subgrad problems
        x_raw = x - step_size * g_val
        x = np.clip(x_raw, x_low, x_high) #actual projection

    cpu_time = time.time() - start_time

    return best_UB, gap, k, cpu_time, UB_hist, LB_hist, gap_hist

# Actual values
dimensions = [2, 5, 10, 100, 500]
results = []

#Figures
fig, axes = plt.subplots(1, len(dimensions), figsize=(20, 4))
fig.suptitle("Subgradient Method Convergence Plots (Gap = UB - LB)", fontsize=16)

for idx, n in enumerate(dimensions):
    ub, gap, iters, cpu_time, ub_hist, lb_hist, gap_hist = run_subgradient(n)

    #Summary table
    results.append({
        'n': n,
        'Method': 'Subgradient',
        'f(x*)': ub,
        'Final Gap': gap,
        'Iterations': iters,
        'CPU Time (s)': cpu_time
    })

    ax = axes[idx]
    ax.plot(gap_hist, label='Gap (UB - LB)', color='green', linewidth=2)
    ax.plot(ub_hist, label='Upper Bound (UB)', color='blue', linestyle='--')
    ax.plot(lb_hist, label='Lower Bound (LB)', color='red', linestyle='--')
    ax.axhline(1e-4, color='black', linestyle=':', label='Tolerance (1e-4)')

    ax.set_title(f"Dimension n={n}")
    ax.set_xlabel("Iteration k")
    ax.set_ylabel("Value")
    ax.set_yscale('symlog') # Symlog helps visualize large initial gaps shrinking to ~0
    if idx == 0:
        ax.legend()

plt.tight_layout()
plt.subplots_adjust(top=0.85)
plt.show()

df = pd.DataFrame(results)
pd.set_option('display.float_format', lambda x: '%.6f' % x)
print("\n" + "="*60)
print(" SUMMARY TABLE: Subgradient Method Scaling (P4)")
print("="*60)
print(df.to_string(index=False))

"""# Problem 4 with new subgradient method"""

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import time

def oracle(x):
    f_val = np.sum(x**2)      # f(x) = ||x||^2
    g_val = 2.0 * x           # g(x) = 2x  (exact gradient, smooth everywhere)
    return f_val, g_val

def run_subgradient(n, x_low=-0.5, x_high=1.0, tol=1e-4, max_iter=10000):
    x     = np.full(n, x_high)        # start at upper bound (worst case)
    bestx = x.copy()
    fbest = oracle(x)[0]

    fbest_hist = []
    dx_hist    = []

    start_time = time.time()

    for k in range(1, max_iter + 1):
        f_val, g_val = oracle(x)

        # update best
        if f_val < fbest:
            fbest = f_val
            bestx = x.copy()

        # step size schedule (scaled to domain size)
        alpha = 0.1 / np.sqrt(k)
        x_new = np.clip(x - alpha * g_val, x_low, x_high)

        # stopping criterion: Euclidean norm of change in x
        dx = np.linalg.norm(x_new - x)

        fbest_hist.append(fbest)
        dx_hist.append(dx)

        x = x_new

        if dx <= tol:
            break

    cpu_time = time.time() - start_time
    return fbest, dx, k, cpu_time, fbest_hist, dx_hist

# ── run over all dimensions ───────────────────────────────────────────────────
dimensions = [2, 5, 10, 100, 500]
results    = []

fig, axes = plt.subplots(2, len(dimensions), figsize=(20, 8))
fig.suptitle("Subgradient Method — f(x) = ||x||₂ on [-0.5, 1]ⁿ", fontsize=14)

for idx, n in enumerate(dimensions):
    fbest, dx, iters, cpu_time, fbest_hist, dx_hist = run_subgradient(n)

    results.append({
        'n':           n,
        'f(x*)':       fbest,
        'Final ||dx||': dx,
        'Iterations':  iters,
        'CPU Time (s)': cpu_time
    })

    # top row: best f value over iterations
    ax_f = axes[0, idx]
    ax_f.plot(fbest_hist, color='blue', linewidth=1.5, label="f(x_best)")
    ax_f.axhline(0, color='black', linestyle=':', label="f* = 0")
    ax_f.set_title(f"n = {n}")
    ax_f.set_xlabel("Iteration k")
    ax_f.set_ylabel("f(x_best)")
    ax_f.set_yscale('log')
    if idx == 0:
        ax_f.legend(fontsize=8)

    # bottom row: ||dx|| over iterations
    ax_dx = axes[1, idx]
    ax_dx.plot(dx_hist, color='green', linewidth=1.5, label="||dx||")
    ax_dx.axhline(1e-4, color='red', linestyle='--', label="tolerance = 1e-4")
    ax_dx.set_xlabel("Iteration k")
    ax_dx.set_ylabel("||dx||")
    ax_dx.set_yscale('log')
    if idx == 0:
        ax_dx.legend(fontsize=8)

plt.tight_layout()
plt.subplots_adjust(top=0.92)
plt.show()

# ── summary table ─────────────────────────────────────────────────────────────
df = pd.DataFrame(results)
pd.set_option('display.float_format', lambda x: '%.6f' % x)
print("\n" + "=" * 65)
print("  SUMMARY TABLE: Subgradient Method Scaling")
print("=" * 65)
print(df.to_string(index=False))

"""# Problem 5

---
Cutting Plane

Function is a maximum of m=20 linear equations to form a polyhedron. Retains memory so it converges more easily. All the cuts allow it to converge by the amount of linear equations (20) at maximum.
"""

import numpy as np
import cvxpy as cp
import matplotlib.pyplot as plt
import pandas as pd
import time

#generate the f and g
def generate_data(m, n, seed=42):
    np.random.seed(seed)
    A = np.random.randn(m, n)
    b = np.random.randn(m)
    return A, b

def oracle_p5(x, A, b):
    vals = A @ x + b
    winning_index = np.argmax(vals)
    return vals[winning_index], A[winning_index]

#define the algorithm
def run_kelley_p5(A, b, n, x_low=-10.0, x_high=10.0, tol=1e-4, max_iter=500):
    x_val = np.full(n, x_high, dtype=float)

    best_UB = float('inf')
    UB_hist, LB_hist, gap_hist = [], [], []
    constraints_list = []

    start_time = time.time()

    for k in range(1, max_iter + 1):
        f_val, g_val = oracle_p5(x_val, A, b)
        best_UB = min(best_UB, f_val)

        constraints_list.append((f_val, g_val, x_val.copy()))

        x = cp.Variable(n)
        theta = cp.Variable()

        constraints = [x >= x_low, x <= x_high]
        for (fi, gi, xi) in constraints_list:
            constraints.append(theta >= fi + gi @ (x - xi))

        prob = cp.Problem(cp.Minimize(theta), constraints)
        prob.solve(solver=cp.HIGHS)

        x_val = x.value
        best_LB = theta.value
        gap = best_UB - best_LB

        UB_hist.append(best_UB)
        LB_hist.append(best_LB)
        gap_hist.append(gap)

        if gap <= tol:
            break

        if time.time() - start_time > 60.0:
            print(f"  [Timeout] n={n} hit 60s limit.")
            break

    cpu_time = time.time() - start_time
    return best_UB, gap, k, cpu_time, UB_hist, LB_hist, gap_hist

#execution
m = 20
dimensions = [1, 2, 10, 100]
results = []

fig, axes = plt.subplots(1, len(dimensions), figsize=(20, 4))
fig.suptitle("Kelley's Method Convergence (P5)", fontsize=16)

for idx, n in enumerate(dimensions):
    A, b = generate_data(m, n)
    ub, gap, iters, cpu_time, ub_hist, lb_hist, gap_hist = run_kelley_p5(A, b, n)

    results.append({'n': n, 'Method': 'Kelley', 'f(x*)': ub, 'Final Gap': gap, 'Iterations': iters, 'CPU Time (s)': cpu_time})

    ax = axes[idx]
    ax.plot(gap_hist, label='Gap (UB - LB)', color='green', linewidth=2)
    ax.plot(ub_hist, label='UB', color='blue', linestyle='--')
    ax.plot(lb_hist, label='LB', color='red', linestyle='--')
    ax.axhline(1e-4, color='black', linestyle=':', label='Tol (1e-4)')
    ax.set_title(f"Dimension n={n}")
    ax.set_xlabel("Iteration k")
    ax.set_yscale('symlog')
    if idx == 0: ax.legend()

plt.tight_layout()
plt.subplots_adjust(top=0.85)
plt.show()

df_kelley = pd.DataFrame(results)
pd.set_option('display.float_format', lambda x: '%.6f' % x)
print("\n=== Kelley's Method Summary (P5) ===")
print(df_kelley.to_string(index=False))

"""# Problem 5

---
Projected Subgradient

Function is a maximum of m=20 linear equations to form a polyhedron. The amount of distance traveled is alpha * norm of the gradient. As you can see, the algorithm failed to converge and never hit the limit tolerance level. Subgradient method is bad at handling sharp creases, which is the product of these linear equations, and just jumps back and forth. Also, since the calculation calls for the minimum of each tangent line, in a system with many dimensions, this minimum has the potential to be huge, making the distance between it and the function larger. Perhaps it would have an easier time converging with a lower step size.
"""

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import time

# generate the f and g for each func
def generate_data(m, n, seed=42):
    np.random.seed(seed)
    A = np.random.randn(m, n)
    b = np.random.randn(m)
    return A, b

def func_p5(x, A, b):
    vals = A @ x + b
    winning_index = np.argmax(vals)
    return vals[winning_index], A[winning_index]

def run_subgradient_p5(A, b, n, x_low=-10.0, x_high=10.0, tol=1e-4, max_iter=100000, window=3000):
    x = np.zeros(n, dtype=float)
    best_UB = float('inf')
    f_hist, best_hist, step_hist = [], [], []

    start_time = time.time()

    for k in range(1, max_iter + 1):
        f_val, g_val = func_p5(x, A, b)
        f_hist.append(f_val)

        if f_val < best_UB:
            best_UB = f_val
        best_hist.append(best_UB)

        g_norm = np.linalg.norm(g_val)


        step_size = (x_high - x_low) / (np.sqrt(k) * g_norm)
        x_prev = x.copy()
        x = np.clip(x - step_size * g_val, x_low, x_high)
        step_change = np.linalg.norm(x - x_prev)
        step_hist.append(step_change)


        if k > window and (best_hist[-window] - best_hist[-1]) < tol:
            break

    cpu_time = time.time() - start_time
    return best_UB, k, cpu_time, f_hist, best_hist, step_hist

# execution
m = 20
dimensions = [1, 2, 10, 100]
results = []
all_data = []
tol = 1e-4

for n in dimensions:
    A, b = generate_data(m, n)
    ub, iters, cpu_time, f_hist, best_hist, step_hist = run_subgradient_p5(A, b, n)
    results.append({'n': n, 'Method': 'Subgradient', 'f(x*)': ub, 'Iterations': iters, 'CPU Time (s)': cpu_time})
    all_data.append((n, f_hist, best_hist, step_hist, iters, ub))

# --- FIGURE 1: Best objective ---
fig1, axes1 = plt.subplots(1, len(dimensions), figsize=(20, 4))
fig1.suptitle("Subgradient Convergence: Best f(x)", fontsize=16)

for idx, (n, f_hist, best_hist, step_hist, iters, ub) in enumerate(all_data):
    ax = axes1[idx]
    ax.plot(best_hist, label='best f(x)', color='red', linewidth=2)
    stride = max(1, len(f_hist) // 200)
    sampled = f_hist[::stride]
    sampled_x = list(range(0, len(f_hist), stride))
    ax.plot(sampled_x, sampled, color='orange', linewidth=1, alpha=0.7, label='f(x) trajectory')
    ax.set_title(f"n={n} | iters={iters} | f*={ub:.4f}")
    ax.set_xlabel("Iteration k")
    ax.set_ylabel("f(x)")
    if idx == 0:
        ax.legend()

plt.tight_layout()
plt.subplots_adjust(top=0.85)
plt.show()

# --- FIGURE 2: Step Change ---
fig2, axes2 = plt.subplots(1, len(dimensions), figsize=(20, 4))
fig2.suptitle("Subgradient Convergence: Step Change", fontsize=16)

for idx, (n, f_hist, best_hist, step_hist, iters, ub) in enumerate(all_data):
    ax = axes2[idx]
    ax.plot(step_hist, label='||x_{k+1} - x_k||', color='green')
    ax.set_title(f"n={n}")
    ax.set_xlabel("Iteration k")
    ax.set_ylabel("Step size")
    ax.set_yscale('log')
    if idx == 0:
        ax.legend()

plt.tight_layout()
plt.subplots_adjust(top=0.85)
plt.show()

df_sub = pd.DataFrame(results)
pd.set_option('display.float_format', lambda x: '%.6f' % x)
print("\n=== Subgradient Method Summary (P5) ===")
print(df_sub.to_string(index=False))

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import time

def generate_data(m, n, seed=42):
    np.random.seed(seed)
    A = np.random.randn(m, n)
    b = np.random.randn(m)
    return A, b

def func_p5(x, A, b):
    vals = A @ x + b
    winning_index = np.argmax(vals)
    return vals[winning_index], A[winning_index]

def run_subgradient_p5(A, b, n, x_low=-10.0, x_high=10.0,
                       tol=1e-4, max_iter=100000):
    x      = np.zeros(n, dtype=float)
    best_x = x.copy()
    fbest  = func_p5(x, A, b)[0]
    f_hist, best_hist, dx_hist = [], [], []
    start_time = time.time()

    for k in range(1, max_iter + 1):
        alpha = 1.0 / np.sqrt(k)
        gx    = func_p5(x, A, b)[1]
        x_new = np.clip(x - alpha * gx, x_low, x_high)

        dx = np.linalg.norm(x_new - x)

        f_new = func_p5(x_new, A, b)[0]
        if f_new < fbest:
            fbest  = f_new
            best_x = x_new.copy()

        f_hist.append(f_new)
        best_hist.append(fbest)
        dx_hist.append(dx)

        x = x_new

        if dx <= tol:
            break

    cpu_time = time.time() - start_time
    return fbest, k, cpu_time, f_hist, best_hist, dx_hist


# --- execution ---
m = 20
dimensions = [1, 2, 10, 100]
tol = 1e-4
results, all_data = [], []

for n in dimensions:
    A, b = generate_data(m, n)
    fbest, iters, cpu_time, f_hist, best_hist, dx_hist = \
        run_subgradient_p5(A, b, n, tol=tol)
    results.append({'n': n, 'Method': 'Subgradient',
                    'f(x*)': fbest,
                    'Iterations': iters, 'CPU Time (s)': cpu_time})
    all_data.append((n, f_hist, best_hist, dx_hist, iters, fbest))


# --- summary table ---
df_sub = pd.DataFrame(results)
pd.set_option('display.float_format', lambda x: '%.6f' % x)
print("\n=== Subgradient Method Summary (P5) ===")
print(df_sub.to_string(index=False))

fig1, axes1 = plt.subplots(1, len(dimensions), figsize=(20, 4))
fig1.suptitle("Subgradient Convergence: Best f(x)", fontsize=16)

for idx, (n, f_hist, best_hist, dx_hist, iters, fbest) in enumerate(all_data):
    ax = axes1[idx]
    ax.plot(best_hist, color='red', lw=2, label='best f(x)')
    stride = max(1, len(f_hist) // 200)
    ax.plot(range(0, len(f_hist), stride), f_hist[::stride],
            color='orange', lw=1, alpha=0.7, label='f(x) trajectory')
    ax.set_title(f"n={n} | iters={iters} | f*={fbest:.4f}")
    ax.set_xlabel("Iteration k")
    ax.set_ylabel("f(x)")
    if idx == 0:
        ax.legend()

plt.tight_layout()
plt.subplots_adjust(top=0.85)
plt.show()

fig2, axes2 = plt.subplots(1, len(dimensions), figsize=(20, 4))
fig2.suptitle("Subgradient Convergence: Step Change", fontsize=16)

for idx, (n, f_hist, best_hist, dx_hist, iters, fbest) in enumerate(all_data):
    ax = axes2[idx]
    ax.plot(dx_hist, color='green', lw=1.5, label='||x_{k+1} - x_k||')
    ax.axhline(tol, color='gray', ls='--', lw=1, label=f"ε={tol}")
    ax.set_yscale('log')
    ax.set_title(f"n={n}")
    ax.set_xlabel("Iteration k")
    ax.set_ylabel("Step size")
    if idx == 0:
        ax.legend()

plt.tight_layout()
plt.subplots_adjust(top=0.85)
plt.show()

"""**Problem 6: Level Method with Applications to Question 4**


---

This is the application of the level method to problem 4 of the project. It is comparable to the Kelley method but addresses several key issues.

The level method is better in high dimensions because it:

1) Avoids extreme-point solutions (which is exactly what Kelley does by finding a global minimum)
2) Controls step size geometrically and finds the level set region from which it finds its next iteration solution
3) Uses the cutting-plane model locally, not globally
4) Maintains centrality, which is critical in high dimensions
5) Reduces sensitivity to model noise
"""

import cvxpy as cp
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import time

def f(x):   return np.dot(x, x)
def g(x):   return 2 * x

dimensions  = [2, 5, 10, 100, 500]
results     = []
historysALL = {}
lam         = 0.05   # level parameter: 0=stay near UB, 1=push toward LB
tolerance   = 0.0001

for n in dimensions:
    print(f"\nRunning n = {n}...")
    x_low  = -0.5 * np.ones(n)
    x_high =  1 * np.ones(n)

    # ── start at corner, far from optimum ────────────────────────────
    x_cur   = x_low.copy()
    best_UB = f(x_cur)
    best_LB = -np.inf
    best_x  = x_cur.copy()

    cuts = [(f(x_cur), g(x_cur), x_cur.copy())]
    UB_hist, LB_hist, gap_hist = [], [], []

    start = time.time()

    for k in range(1, 1000):

        # ── Step 1: LP to update LB ───────────────────────────────────
        x_var  = cp.Variable(n)
        theta  = cp.Variable()
        lp_cons = [x_var >= x_low, x_var <= x_high]
        for (fi, gi, xi) in cuts:
            lp_cons.append(theta >= fi + gi @ (x_var - xi))

        cp.Problem(cp.Minimize(theta), lp_cons).solve(solver=cp.HIGHS)
        best_LB = max(best_LB, theta.value)

        gap = best_UB - best_LB
        UB_hist.append(best_UB)
        LB_hist.append(best_LB)
        gap_hist.append(gap)

        if k % 100 == 0:
            print(f"  k={k:4d} | UB={best_UB:.6f} | LB={best_LB:.6f} | gap={gap:.6f}")

        if gap <= tolerance:
            print(f"  -> Converged at iteration {k}!")
            break

        # ── Step 2: compute level ─────────────────────────────────────
        level = lam * best_LB + (1 - lam) * best_UB

        # ── Step 3: project onto level set ───────────────────────────
        x_var2    = cp.Variable(n)
        proj_cons = [x_var2 >= x_low, x_var2 <= x_high]
        for (fi, gi, xi) in cuts:
            proj_cons.append(fi + gi @ (x_var2 - xi) <= level)

        proj_prob = cp.Problem(cp.Minimize(cp.sum_squares(x_var2 - best_x)), proj_cons)
        proj_prob.solve(solver=cp.HIGHS)

        if proj_prob.status not in ("optimal", "optimal_inaccurate") or x_var2.value is None:
            print(f"  -> Projection infeasible at k={k}, stopping.")
            break

        x_cur = x_var2.value

        # ── update UB from the new projected point ────────────────────
        fx_cur = f(x_cur)
        if fx_cur < best_UB:
            best_UB = fx_cur
            best_x  = x_cur.copy()

        # add new cut at projected point
        cuts.append((f(x_cur), g(x_cur), x_cur.copy()))

    elapsed = time.time() - start
    historysALL[n] = {'UB': UB_hist, 'LB': LB_hist, 'Gap': gap_hist}
    results.append({
        'n': n, 'f(x*)': best_UB, 'Final Gap': gap,
        'Iterations': k, 'CPU Time (s)': elapsed
    })

# ── summary table ─────────────────────────────────────────────────────────────
df = pd.DataFrame(results)
pd.set_option('display.float_format', lambda x: '%.6f' % x)
print("\n=== Level Method Summary (Problem 4) ===")
print(df.to_string(index=False))

# ── convergence plots ─────────────────────────────────────────────────────────
fig1, axes = plt.subplots(1, len(dimensions), figsize=(20, 4))
fig1.suptitle("Level Method Convergence (UB, LB, Gap) — f(x)=||x||² on [-0.5,1]ⁿ")

for idx, n in enumerate(dimensions):
    ax   = axes[idx]
    hist = historysALL[n]
    ax.plot(hist['Gap'], color='green',   linewidth=2,    label='Gap')
    ax.plot(hist['UB'],  color='blue',    linestyle='--', label='UB')
    ax.plot(hist['LB'],  color='red',     linestyle='--', label='LB')
    ax.axhline(tolerance, color='black',  linestyle=':',  label='Tol')
    ax.set_title(f"n = {n}")
    ax.set_xlabel("Iteration k")
    ax.set_yscale('symlog')
    if idx == 0: ax.legend()

plt.tight_layout()
plt.show()

# ── scaling plots ─────────────────────────────────────────────────────────────
fig2, (ax_iter, ax_time) = plt.subplots(1, 2, figsize=(12, 4))
ns    = [r['n'] for r in results]
iters = [r['Iterations'] for r in results]
times = [r['CPU Time (s)'] for r in results]

ax_iter.plot(ns, iters, marker='o')
ax_iter.set_xscale('log'); ax_iter.set_xticks(ns); ax_iter.set_xticklabels(ns)
ax_iter.set_title("Iterations vs n"); ax_iter.set_xlabel("n"); ax_iter.set_ylabel("Iterations")

ax_time.plot(ns, times, marker='o', color='orange')
ax_time.set_xscale('log'); ax_time.set_xticks(ns); ax_time.set_xticklabels(ns)
ax_time.set_title("CPU Time vs n"); ax_time.set_xlabel("n"); ax_time.set_ylabel("Time (s)")

plt.tight_layout()
plt.show()